.pnp.cjs
package.json
src/components/common/Button/Button.stories.tsx
src/components/common/Button/index.tsx
yarn.lock

close #1 
- 스토리북 배포 확인을 위한 임시 버튼 컴포넌트 작성

[CHORE] 스토리북 배포 테스트

---

src/styles/Color.mdx
src/styles/global.ts

close #6 
- 전역 색상 값을 등록합니다.
- 색상 정보를 확인할 수 있는 스토리북을 작성합니다.
- 컬러값 사용 방법 예시
```javascript
import { colors } from '@/styles/global';
const StyledDiv = styled.div`
background-color: ${colors.BK};
`
```

[FEAT] global color palette, 스토리북

---

src/components/common/FlexBox/FlexBox.stories.tsx
src/components/common/FlexBox/FlexBox.styled.ts
src/components/common/FlexBox/FlexBox.types.ts
src/components/common/FlexBox/index.tsx

close #15 
- FlexBox 컴포넌트와 스토리북을 작성합니다.
- 스토리북을 통해 컴포넌트 사용 방법 확인 가능합니다.

[FEAT] FlexBox 컴포넌트, 스토리북

---

src/components/common/Button/Button.stories.tsx
src/components/common/Button/Button.styled.ts
src/components/common/Button/Button.types.ts
src/components/common/Button/index.tsx
src/styles/Color.mdx
src/styles/global.ts

#9 
- Button 컴포넌트의 CTA 버튼 작업만 완료하였습니다. 
- 추후 디자인 작업이 완료되면 더 추가해야 될 것 같습니다! 따라서 해당 이슈 아직 close 하지 않겠습니당
- 디자인을 보니 각 버튼마다 padding이 달라 어떻게 해야할 지 고민이 됩니다.. 🫨
- 버튼 props로 추가했으면 좋겠는 부분 말씀해주시면 반영하겠습니다!!

[FEAT] Button 컴포넌트, 스토리북

---

src/components/common/FlexBox/FlexBox.stories.tsx
src/components/common/FlexBox/FlexBox.styled.ts
src/components/common/FlexBox/FlexBox.types.ts
src/components/common/FlexBox/index.tsx

- FlexBox 컴포넌트에 ref를 붙이기 위해 forwardRef를 사용합니다.
- gap prop에 string 타입을 추가합니다.
- `gap={0}` 인 경우, `gap: 0px` // 숫자라면 px 값으로 전달됩니다.
- `gap='20px'` 인 경우, `gap: 20px` // 문자열이라면 그대로 전달됩니다.
- flex-wrap prop을 추가합니다.

[FIX] FlexBox 구현체 및 Props 수정

---

src/components/common/Chip/Chip.stories.tsx
src/components/common/Chip/Chip.styled.ts
src/components/common/Chip/Chip.types.ts
src/components/common/Chip/index.tsx

close #7 
close #20 
- Chip 컴포넌트와 스토리북을 작성합니다.
- ChipGroup 컴포넌트와 스토리북을 작성합니다.
- Chip을 버튼으로 사용하고자할 경우, 다음과 같이 사용해 주세요. (스토리북 코드 참고!)
```tsx
<Chip component='button'>칩 버튼</Chip>
```
- 여러 개의 Chip을 배치하는 경우, 다음과 같이 Chip.Group으로 래핑해 주세요. (스토리북 코드 참고!)
```tsx
<Chip.Group>
<Chip>칩1</Chip>
<Chip>칩2</Chip>
<Chip>칩3</Chip>
</Chip.Group>
```
- #19 가 머지 된 다음, TODO 수정 후 머지할 예정입니다.

[FEAT] Chip 컴포넌트, 스토리북

---

src/components/common/Typography/index.tsx

close #21 
- Typography 컴포넌트에 텍스트 컬러 변경을 위한 color 프롭을 추가합니다.

[FEAT] Typography에 color 프롭 추가

---

src/components/common/Button/Button.styled.ts
src/components/common/Button/index.tsx
src/components/common/Slider/Slider.stories.tsx
src/components/common/Slider/Slider.styled.ts
src/components/common/Slider/Slider.types.ts
src/components/common/Slider/index.tsx

close #10 
- Slider 컴포넌트와 스토리북을 작성합니다.
- 사용 방법은 스토리북 코드 참고해주세요!

[FEAT] Slider 컴포넌트

---

_templates/component/common/index.ejs.t
_templates/component/common/types.ejs.t

close #31 
- `{Component}.types.ts` 파일 템플릿 추가
- index.tsx에서 작성한 Props 타입을 styled에 import 하여 사용하고 다시 스타일드 컴포넌트를 export하는 과정에서 순환 참조가 발생하여 type을 따로 관리하고자 합니다.
- `hygen component common`을 입력하면 기존과는 다르게 `Component.types.ts` 파일이 하나 더 생깁니다!

[FIX] 공통 컴포넌트 제너레이터 템플릿 수정

---

.storybook/preview.ts
public/icons/delete-rounded.svg
src/components/common/TextField/TextField.stories.tsx
src/components/common/TextField/TextField.styled.ts
src/components/common/TextField/TextField.types.ts
src/components/common/TextField/index.tsx
src/index.css
src/styles/global.ts

close #8 
- TextField 컴포넌트와 스토리북을 작성합니다.
- 수정된 디자인 반영되었습니다!

[FEAT] TextField 컴포넌트, 스토리북

---

src/components/common/IconButton/IconButton.stories.tsx
src/components/common/IconButton/IconButton.styled.ts
src/components/common/IconButton/IconButton.types.ts
src/components/common/IconButton/index.tsx

close #26 
- IconButton 컴포넌트와 스토리북을 작성합니다.
- #39 기반으로 한 작업이라 39 PR 선머지 필요합니다.

[FEAT] IconButton 컴포넌트, 스토리북

---

src/components/common/Chip/Chip.stories.tsx
src/components/common/Chip/Chip.styled.ts
src/components/common/Chip/Chip.types.ts

close #50 
- greyFilled 버라이언트를 추가합니다. (프로그레스 표현하는 부분)
- 기존 display용 Chip의 패딩을 수정합니다.

[FEAT] Chip 디자인 반영

---

src/components/common/Slider/Slider.stories.tsx
src/components/common/Slider/Slider.styled.ts
src/components/common/Slider/Slider.types.ts
src/components/common/Slider/index.tsx

close #34
- Slider 컴포넌트, 스토리북 생성
- css가 엄청나서.. 지워도 되거나 수정하면 좋을 부분 말씀해주시면 감사하겠습니다..ㅠㅡㅠ

[FEAT] Slider 컴포넌트, 스토리북

---

src/App.tsx
src/components/common/AppLayout/AppLayout.styled.ts
src/components/common/AppLayout/AppLayout.types.ts
src/components/common/AppLayout/index.tsx

[FEAT] App layout

---

src/components/common/Button/Button.styled.ts

close #57 
- Button 컴포넌트 disabled값에 따라 `not-allowed` `pointer` 지정하는 것만 수정했습니다.

[FEAT] Button 컴포넌트 cursor 지정

---

src/components/common/FixedBottomButton/FixedBottomButton.stories.tsx
src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
src/components/common/FixedBottomButton/FixedBottomButton.types.ts
src/components/common/FixedBottomButton/index.tsx

close #35
- FixedBottomButton 컴포넌트, 스토리북 구현하였습니다.
- 사용 방법은 스토리북 참고해주세욥!

[FEAT] FixedBottomButton 컴포넌트, 스토리북

---

src/components/common/Typography/Typography.mdx
src/components/common/Typography/Typography.styled.ts
src/components/common/Typography/index.tsx

close #43 
- Head4, Body4 컴포넌트를 추가합니다.
- 몇몇 폰트 크기 수정합니다.

[FEAT] Typography 변경된 디자인 반영

---

src/components/common/AppLayout/AppLayout.styled.ts

close #65 
- width: 393px -> max-width: 430px 으로 수정합니다.
- 큰 폰 사이즈(아이폰 14 프로 맥스)의 너비를 기준으로 max-width 변경했습니다

[FIX] AppLayout max-width 수정

---

src/components/common/Button/Button.stories.tsx
src/components/common/Chip/Chip.stories.tsx
src/components/common/FixedBottomButton/FixedBottomButton.stories.tsx
src/components/common/FixedBottomButton/index.tsx
src/components/common/FlexBox/FlexBox.stories.tsx
src/components/common/FlexBox/FlexBox.styled.ts
src/components/common/FlexBox/FlexBox.types.ts
src/components/common/FlexBox/index.tsx
src/components/common/IconButton/IconButton.stories.tsx

close #54 
- **인터페이스 수정** (브레이킹체인지....)
- alignItem -> alignItems로 이름 변경합니다.
- 프롭 추가
- width, height 프롭을 추가합니다.
- as 프롭을 추가합니다.
- FlexBox를 section 태그로 렌더링하고 싶은 경우 다음과 같이 사용합니다.
```tsx
<FlexBox as='section' />
```

[FEAT] FlexBox 컴포넌트에 프롭 추가

---

src/pages/Login.tsx

close #76 
- 로그인 페이지의 alignItem 워딩을 alignItems로 변경 시켰습니다.

[BUGFIX] alignItems 워딩 수정

---

src/components/common/Header/Header.stories.tsx

close #78 
- 헤더에서 아이콘의 변경 전 네이밍을 사용 중인 부분이 있어 변경 후 네이밍을 사용하도록 수정합니다.
- JjakkakText -> jjakkakText

[BUGFIX] 헤더에서 변경된 네이밍 사용 중인 부분 수정

---

.github/labeler-config.yaml

close #80 
- 버그픽스 PR을 작성했을 때 fix 라벨을 붙입니다.

[CHORE] 버그픽스 PR 생성 시 fix 라벨 지정

---

.pnp.cjs
package.json
yarn.lock

close #75 
- lint 커맨드에 타입스크립트 컴파일러 커맨드를 추가합니다.
- 타입스크립트 버전을 다운그레이드합니다. (5.5.3 -> ~5.3.0)

[BUGFIX] typescript 다운그레이드, lint 커맨드 수정

---

src/components/common/FixedBottomButton/FixedBottomButton.stories.tsx
src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
src/components/common/FormLayout/FormLayout.stories.tsx
src/components/common/FormLayout/FormLayout.types.ts
src/components/common/FormLayout/index.tsx
src/components/common/Header/index.tsx
src/components/features/CreateMeetingForm/AnonymousForm.tsx
src/components/features/CreateMeetingForm/CategoryForm.tsx
src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx
src/components/features/CreateMeetingForm/DeadlineForm.tsx
src/components/features/CreateMeetingForm/MeetingNameForm.tsx
src/components/features/CreateMeetingForm/MemberForm.tsx
src/components/features/CreateMeetingForm/PeriodForm.tsx
src/components/features/CreateMeetingForm/index.ts
src/components/features/CreateMeetingForm/types.ts
src/constants/meetingForm.ts
src/contexts/FunnelProgressContext.tsx
src/hooks/useFunnel.tsx
src/hooks/useFunnelProgressContext.tsx
src/pages/NewMeeting.tsx
src/routes/route.tsx

close #70 
- 모임 생성에 필요한 폼 컴포넌트 작성 (아직 라이팅이 픽스되지 않아 하드코딩으로 넣어둡니다...)
- 카테고리 선택 : `<CategoryForm/>`
- 모임 이름 입력 : `<MeetingNameForm/>`
- 모임 일정 수집 기한 : `<DateForm/>`
- 모임 인원수 선택 : `<MemberForm/>`
- 익명 여부 선택 : `<AnonymousForm/>`
- 마감 기한 선택 : `<DeadlineForm/>`
- FixedBottomButton css 수정
- 컴포넌트가 페이지 하단에 고정될 수 있도록 css를 수정합니다.
- Header 수정
- div에서 header 태그로 변경합니다.
- 컴포넌트가 페이지 상단에 고정될 수 있도록 css를 수정합니다.
- FormLayout 컴포넌트 수정
- FormLayout 내부의 헤더를 제거하고 prop을 통해 받도록 수정합니다.
- 수정한 이유: FormLayout이 퍼널의 흐름과 관련된 것(e.g. `onPrevious`, `progress`)까지 prop으로 받는게 어색하다고 느껴져서, FormLayout은 Presentational로만 활용하기 위해 제거했습니다.
- 불필요한 gitkeep 파일 삭제
- Progress를 표시하기 위해 각각의 폼 컴포넌트들이 마지막 스텝과 현재 스텝을 알아야 하는데, 이 데이터를 어떻게 주입하면 좋을까요? 스텝에 관한 컨텍스트를 만드는게 좋을까요...🤔 (현재는 TODO 주석과 함께 하드코딩 되어 있습니다)

[FEAT] 모임 생성 페이지 UI

---

src/components/common/Chip/Chip.stories.tsx
src/components/common/Chip/Chip.styled.ts
src/components/common/Chip/Chip.types.ts
src/components/common/Chip/index.tsx

close #107 
- Chip을 버튼으로 사용할 때, 라벨과 밸류가 다를 수 있는 경우를 대응하기 위해 value 프롭을 추가합니다.

[FEAT] Chip에 value 프롭 추가

---

src/components/common/Chip/Chip.styled.ts
src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
src/components/common/Switch/Switch.styled.ts
src/components/features/CreateMeetingForm/AnonymousForm.tsx
src/components/features/CreateMeetingForm/CategoryForm.tsx
src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx
src/components/features/CreateMeetingForm/DeadlineForm.tsx
src/components/features/CreateMeetingForm/DueDateForm.tsx
src/components/features/CreateMeetingForm/MeetingDateRangeForm.tsx
src/components/features/CreateMeetingForm/MeetingNameForm.tsx
src/components/features/CreateMeetingForm/MemberCountForm.tsx
src/components/features/CreateMeetingForm/MemberForm.tsx
src/components/features/CreateMeetingForm/PeriodForm.tsx
src/components/features/CreateMeetingForm/index.ts
src/constants/meetingForm.ts
src/pages/NewMeeting.tsx

close #100 
https://github.com/user-attachments/assets/d3167481-066a-4130-8587-4581ea9ce340
- 각 폼은 지역 상태를 가지고 있으며 해당 상태를 가지고 간단한 유효성 검사를 수행합니다.
- #102 선머지 필요한 PR입니다. (머지 되면 lint error 해결 가능합니다.)
- 후속 작업 이슈 (퍼널이 많아 작업이 길어질 것 같아 별도의 이슈로 분리합니다.)
- #104
- #105 
별거 없긴한데 그냥 리뷰어 걸어봅니다..ㅎㅎ (changes가 좀 많긴한데 pnp 파일 때문이니...눈감아주세요 ㅎ)

[FEAT] 모임 생성 폼 로직 작성

---

src/components/common/Chip/Chip.stories.tsx
src/components/common/Chip/Chip.styled.ts
src/components/common/Chip/Chip.types.ts
src/components/common/Chip/index.tsx
src/components/common/FormLayout/index.tsx
src/components/common/Header/Header.stories.tsx
src/components/features/CreateMeetingForm/CategoryForm.tsx
src/styles/global.ts

close #85 
- Chip에 `shape?: 'rounded' | 'rectangle'` 프롭을 추가합니다.
- 기본값=`rounded`
- Chip의 `variant` 프롭 값들을 추가하고 일부 네이밍 수정했습니다.
- `filled -> primary`
- `greyFilled -> grey`
- `secondary` `primaryReverse` `greyWeak` 추가
- 브레이킹 체인지를 담고 있어서 Chip 사용하는 PR 머지할 때 충돌 마니 날 것 같아욥 (특히 제 PR ㅠㅎ)

[FEAT] Chip 버라이언트 및 스크롤 그룹 추가

---

src/components/features/MemberCard/MemberCard.stories.tsx
src/components/features/MemberCard/MemberCard.styled.ts
src/components/features/MemberCard/MemberCard.types.ts
src/components/features/MemberCard/index.tsx

close #113 
- 다음과 같은 상황에서 사용하는 MemberCard 컴포넌트입니다!

[FEAT] MemberCard 컴포넌트, 스토리북 구현

---

src/components/common/Calendar/Calendar.styled.ts
src/components/common/Calendar/Calendar.types.ts
src/components/common/Calendar/index.tsx
src/hooks/useCalendar.tsx

close #132 
- Calendar 지난 날짜 dim처리했습니다. 
https://github.com/user-attachments/assets/0bdf327b-d490-467e-b956-399884e62213

[REFACTOR] Calendar 지난 날짜 dim처리

---

src/apis/index.ts
src/apis/member/api.ts
src/apis/member/queries.ts
src/apis/member/type.ts
src/components/features/KakaoLoginButton/KakaoLoginButton.styled.ts
src/components/features/KakaoLoginButton/index.tsx
src/constants/endpoint.ts
src/hooks/useAuth.tsx
src/lib/axios.ts
src/main.tsx
src/pages/Login.tsx
src/pages/LoginFailure.tsx
src/pages/LoginSuccess.tsx
src/routes/PrivateRoute.tsx
src/routes/route.tsx

close #59 
카카오 로그인 버튼을 클릭하여 로그인을 진행한 다음, 로그인 성공 여부에 따라 아래와 같은 페이지로 리다이렉트 됩니다.
- 성공 시, `/login/success`
- 해당 페이지에서 액세스 토큰을 발급하고 로컬 스토리지에 저장합니다.
- 실패 시, `/login/failure`
- 로그인 실패 알럿을 띄우고, Login 페이지로 리다이렉트합니다.
👇 스크린샷
https://github.com/user-attachments/assets/932c8ddf-4c0f-4681-a43a-71313bfeeb09
로그인된 유저가 로그인 페이지에 접근할 수 없도록, 로그인 페이지 접근 시 권한 검사를 수행합니다.
```tsx
export const Login = () => {
const { isAuthenticated } = useAuth(); // useAuth에서는 로컬스토리지에 저장된 토큰 값으로 서버에 검증 요청을 보냅니다.
if (isAuthenticated) {
return <Navigate to="/" />;
}
```
👇 스크린샷
https://github.com/user-attachments/assets/0bfc5729-00a2-4cc8-afde-baa9a7b0fea8
모임 생성 페이지와 같이 인증된 유저만 접근 가능한 페이지에 비회원이 접근한 경우 로그인 페이지로 리다이렉트합니다.
접근을 막고자 하는 페이지는 `PrivateRoute`로 감싸주면 됩니다.
`PrivateRoute` 내부에서는 로컬 스토리지에 저장된 토큰값으로 서버에 유효한 토큰인지 검사하고, 유효하다면 접근 허용 …

[FEAT] 로그인 기능 구현

---

src/components/common/Border/Border.stories.tsx
src/components/common/Border/Border.styled.ts
src/components/common/Border/Border.types.ts
src/components/common/Border/index.tsx

close #130 
- Border 컴포넌트와 스토리북을 추가합니다.

[FEAT] Border 컴포넌트, 스토리북

---

src/components/features/CreateMeetingForm/DueDateForm.tsx
src/components/features/CreateMeetingForm/types.ts
src/pages/NewMeeting.tsx

close #138 
- ASIS
- 모임 시작 날짜와 관계 없이 오늘/내일/3일/5일 선택지 모두 노출
- TOBE
- 모임 시작 날짜 이전에 해당하는 선택지만 노출
- Switch의 디자인(선택지 배치 형식)은 디자이너와 논의 후에 반영할 예정입니다.

[FEAT] 일정 마감 기한 선택지 조건부 노출

---

src/components/common/Header/Header.stories.tsx
src/components/common/Header/Header.styled.ts
src/components/common/Header/index.tsx

close #144 
||screenshot|
|----|----|
|asis|<img width="433" alt="스크린샷 2024-09-18 오전 12 18 44" src="https://github.com/user-attachments/assets/7f98ef29-f209-49ca-a79a-ccf95565f493">|
|tobe|<img width="433" alt="스크린샷 2024-09-18 오전 12 18 34" src="https://github.com/user-attachments/assets/e687eda3-6a7c-47a9-b74a-20c398a09ac7">|
- 가운데 요소가 수평중앙정렬 되도록 css를 수정합니다.
- 관련 케이스 스토리를 추가합니다.

[FEAT] 헤더 UI 개선

---

src/components/common/Slider/Slider.stories.tsx
src/components/common/Slider/Slider.styled.ts

close #150 
- Slider 스토리북 수정했습니다. 
- `handleChange` 함수의 조건문을 추가하여 2보다 클 경우에만 상태 변경이 가능하도록 수정했습니다.

[BUGFIX] Slider 스토리북 수정

---

src/components/common/IconButton/IconButton.stories.tsx
src/components/common/IconButton/IconButton.types.ts
src/components/common/IconButton/index.tsx

close #168  
- IconButton에 iconColor 프롭을 추가합니다.
- 관련 스토리북을 작성합니다.

[FEAT] IconButton에 iconColor 프롭 추가

---

src/components/features/CreateMeetingForm/CategoryForm.tsx
src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx
src/components/features/CreateMeetingForm/Summary.tsx
src/constants/meetingForm.ts
src/main.tsx
src/pages/NewMeeting.tsx
src/pages/NewMeetingShare.tsx
src/routes/route.tsx

close #105 
- 입력값을 확인하는 Summary 페이지 마크업
- Summary 페이지에서 일정 생성하기 버튼 클릭 시 mutation 호출
- 모임 생성 후 이어질 링크 공유 페이지 마크업

[FEAT] 모임 생성 api 연결

---

src/assets/icons/add.svg
src/assets/icons/index.tsx
src/components/common/AppLayout/AppLayout.styled.ts
src/components/common/FloatingActionButton/FloatingActionButton.stories.tsx
src/components/common/FloatingActionButton/FloatingActionButton.styled.ts
src/components/common/FloatingActionButton/FloatingActionButton.types.ts
src/components/common/FloatingActionButton/index.tsx

close #157 
- FloatingActionButton 컴포넌트와 스토리북을 추가합니다.
- AppLayout에 position: relative를 넣어서 사이드 이펙이 생길지도 모르겠습니닷...혹시 보이면 말씀해 주세요

[FEAT] FloatingActionButton 컴포넌트, 스토리북

---

src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx
src/components/features/CreateMeetingForm/MemberCountForm.tsx

close #160 
- min 값을 2에서 0으로 수정합니다 (UI 맞추기 위한 목적)

[FEAT] 모임 생성 폼에서 Slider의 Min 값 수정

---

src/components/common/ScheduleInput/index.tsx
src/components/common/TimeRangePicker/TimeRangePicker.styled.ts

close #162 
- ScheduleInput border처리, IconButton 변경했습니다.

[FIX] ScheduleInput border처리, IconButton 변경

---

src/components/common/ScheduleLayout/ScheduleLayout.stories.tsx
src/components/common/ScheduleLayout/ScheduleLayout.styled.ts
src/components/common/ScheduleLayout/ScheduleLayout.types.ts
src/components/common/ScheduleLayout/index.tsx

close #166 
- ScheduleLayout 스토리북, 컴포넌트 구현했습니다.

[FEAT] ScheduleLayout 스토리북, 컴포넌트 구현

---

src/components/features/CreateScheduleForm/CreateScheduleForm.stories.tsx
src/components/features/CreateScheduleForm/NickNameForm.tsx
src/components/features/CreateScheduleForm/ScheduleInputForm.tsx
src/components/features/CreateScheduleForm/types.ts
src/constants/scheduleFrom.ts
src/pages/NewSchedule.tsx
src/types/schedule.ts

close #120 
- ScheduleForm 폼 로직 생성했습니다.
https://github.com/user-attachments/assets/c529d5a9-d817-4b52-8513-3057fcde0103
- 시간 입력하는 TimeRangePicker가 스크롤과 선택을 구분하지 못해서, TimeRangePicker부분을 스크롤하려하면 시간 선택이 됩니다..🥲  개선하거나 사용자에게 스크롤은 스크롤바를 사용해야 한다는 인식을 주고 싶은데 어떤게 좋은 방법일지 고민됩니다..!

[FEAT] ScheduleForm 폼 로직 생성

---

src/apis/member/api.ts
src/lib/axios.ts

close #173 
- 요청 헤더에 reissue 여부를 확인하는 플래그가 누락되어 추가했습니다.
- 테스트 완료 (check 401 받으면 reissue 자동 요청 후 200 응답 확인)

[BUGFIX] interceptor의 reissue 미동작 해결

---

src/components/common/Chip/Chip.stories.tsx
src/components/common/Chip/Chip.styled.ts
src/components/common/Chip/Chip.types.ts

close #156 
- primaryWeak 버라이언트 추가합니다.

[FEAT] Chip에 primaryWeak 버라이언트 추가

---

src/hooks/useSchedule.tsx
src/utils/parseTimeRanges.ts

close #170 
- parseTimeRanges 함수 수정했습니다. 변경 사항은 다음과 같습니다.
1. 백엔드 API에 맞게 배열 객체 형식을 띈 데이터 구조로 변경했습니다.
2. 24:00:00가 데이터로 들어올 경우 dayjs는 다음날 자정으로 인식합니다. 따라서 endHour를 배열의 마지막 인덱스(15, 즉 23:00 ~ 24:00)로 설정합니다. 
예를 들면, 2024-09-01T24:00:00은 실제로 2024-09-02T00:00:00"와 같기 때문에, 이를 9월 1일의 마지막 시간으로 처리하기 위해 조건문을 추가했습니다!
```
if (endDate.hour() === 0 && endDate.minute() === 0 && endDate.second() === 0) {
endHour = TOTAL_TIME - 1;
}
```
- 요 PR 머지 되면 수정 폼 로직 올리겠습니다!

[FIX] parseTimeRanges 함수 수정

---

src/pages/PinRelease.tsx

close #165 
- 식별자 확인 페이지 구현했습니다.
- 추후 논의 후 디자인 변경 필요합니다.
- 
- `PinRelease` 괜찮은가요..?

[FEAT] 식별자 확인 페이지 구현

---

src/pages/TotalSchedule.tsx

close #178 
- 일정 결과 전체조회 페이지 UI 작업했습니다. (추후 API 연결 후 더 손봐야 할 것 같아욥!)
<div style={{ display: 'flex', flexDirection: 'row' }}>
</div>

[FEAT] 일정 결과 전체조회 페이지 UI 작업

---

src/components/common/AppLayout/AppLayout.styled.ts

close #109 
(CTA 위치는 무시해주셔용)
|as-is(bg 컬러가 100vh만큼만 적용되어 스크롤 발생 시 흰배경 나타남)|to-be|
|-----|-----|
|<img width="426" alt="스크린샷 2024-09-21 오후 8 25 58" src="https://github.com/user-attachments/assets/aad8313f-a645-44e9-8b15-9c2188d0a254">|<img width="426" alt="스크린샷 2024-09-21 오후 8 26 07" src="https://github.com/user-attachments/assets/ef33c2d1-9567-450c-a208-2bc4c1acb81d">|

[BUGFIX] 스크롤 화면일 때 배경색 사라지지 않도록

---

src/components/common/Header/index.tsx

close #183 
- 컬러 타입을 컬러값으로 파싱하는 코드를 추가합니다.

[BUGFIX] 헤더에 배경색 적용되도록

---

src/components/features/MeetingList/MeetingList.stories.tsx
src/components/features/MeetingList/index.tsx
src/pages/Meeting.tsx
src/routes/route.tsx
src/types/meeting.ts
src/utils/isPastDate.ts

[FEAT] 모임 목록 페이지 UI

---

src/components/features/EditScheduleForm/EditScheduleForm.stories.tsx
src/components/features/EditScheduleForm/EditScheduleInputForm.tsx
src/components/features/EditScheduleForm/PinInputForm.tsx
src/components/features/EditScheduleForm/types.ts
src/pages/EditSchedule.tsx

close #153 
-일정 수정 폼 로직 작성, 스토리북 구혔습니다!
https://github.com/user-attachments/assets/c81ee190-03c4-4337-bb28-ffd459712d11

[FEAT] 일정 수정 폼 로직 작성

---

src/pages/NewMeetingShare.tsx

close #194 
|asis|tobe|
|----|-----|
|<img width="426" alt="스크린샷 2024-09-21 오후 11 14 41" src="https://github.com/user-attachments/assets/abc8906a-90e1-4700-9799-31597f27243d">|<img width="426" alt="스크린샷 2024-09-21 오후 11 22 23" src="https://github.com/user-attachments/assets/de73f889-d425-4d87-a5ac-b8d2911dcbc8">|
- UI 수정합니다.
- 각 버튼에 핸들러 연결했습니다. (navigate)
- `내 일정 입력하기` 내비게이트 주소 맞는지 확인 부탁드립니다!

[FIX] 모임 생성 후 링크 공유 페이지의 CTA 수정

---

src/components/common/ScheduleLayout/ScheduleLayout.styled.ts

close #202 
- ScheduleLayout 그라데이션 높이 지정해줬습니다!

[FIX] ScheduleLayout 그라데이션 높이 지정

---

src/components/features/MeetingDetail/MeetingDetail.stories.tsx
src/components/features/MeetingDetail/index.tsx
src/pages/MeetingDetail.tsx
src/utils/formatDateTime.ts

close #192 
- MeetingDetail 페이지 UI 작업했습니다. (dueDateTime을 지난 경우/ 입력이 없는 경우 입니다!)
<div style={{ display: 'flex', flexDirection: 'row' }}>
<img
width="309"
alt="스크린샷 2024-09-21 오후 11 48 40"
src="https://github.com/user-attachments/assets/dc9f7b07-4adc-4d1d-97e6-2c5ae45a6737"
/>
<img
width="323"
alt="스크린샷 2024-09-21 오후 11 49 16"
src="https://github.com/user-attachments/assets/7bf9735c-234b-4fe4-a5b5-42670bc80d70"
/>
</div>

[FEAT] MeetingDetail 페이지 UI

---

src/styles/global.ts

close #208 
- ScheduleLayout에 사용할 color 추가했습니다.

[FEAT] Color 추가

---

src/components/common/ScheduleLayout/ScheduleLayout.styled.ts
src/components/common/ScheduleLayout/index.tsx

close #209
-  ScheduleLayout background color `lightPurple`로 변경했습니다.

[FEAT] ScheduleLayout background color 변경

---

src/pages/PinRelease.tsx

close #215 
- 식별자 페이지 UI 수정했습니다.

[FEAT] 식별자 페이지 UI 수정

---

src/apis/meeting/api.ts
src/apis/meeting/queries.ts
src/components/features/TotalScheduleList/TotalScheduleList.tsx
src/components/features/TotalScheduleList/TotalScheduleList.type.ts
src/pages/TotalSchedule.tsx

close #205 
- 일정 전체 조회 API 연결했습니다.

[FEAT] 일정 전체 조회 API 연결

---

src/components/common/TimeRangePicker/TimeRangePicker.styled.ts
src/pages/PinRelease.tsx

close #228 
- 식별자 state 받아서 노출 연결했습니다.
- TimePicker colorIndex 수정도 함께 진행했습니다..!

[FEAT] 식별자 state 노출

---

src/assets/icons/index.tsx
src/pages/NotFound.tsx
src/routes/route.tsx

close #226 
- axios 기본적인 retry 3회 이후 NotFound 페이지로 이동하게 됩니다!
- 요 부분에도 추가되어야 할 것 같습니당
```
mutationCache: new MutationCache({
onError: () => {
alert('mutation error'); // TODO
},
}),
```

[FEAT] NotFound 페이지 구현

---

src/components/common/PinInput/PinInput.types.tsx
src/components/common/PinInput/index.tsx
src/components/features/EditScheduleForm/EditScheduleContent.tsx
src/components/features/EditScheduleForm/PinInputForm.tsx
src/components/features/EditScheduleForm/types.ts
src/pages/EditSchedule.tsx

close #176
- PinInput helper 추가 되면서 EditSchedule 컴포넌트 내에서 `useQuery`를 불러 오는 것으로 변경했습니당

[FEAT] PinInput helper 추가

---

src/apis/meeting/api.ts
src/apis/meeting/queries.ts
src/apis/meeting/type.ts
src/components/features/TotalScheduleList/TotalScheduleList.tsx
src/components/features/TotalScheduleList/TotalScheduleList.type.ts
src/pages/TimeCollection.tsx
src/pages/TotalSchedule.tsx

close #239 
- 모임 일정 시간 조회 무한 스크롤 기능 구현했습니다.
- 모임 일정 전체 시간 조회도 수정하였습니다.

[FEAT] 모임 일정 시간 조회 무한 스크롤 기능

---

src/components/features/MeetingDetail/MeetingInfo.tsx
src/utils/formatDate.ts

close #247
- Date YYYY. MM. DD 형식에 맞도록 수정했습니다.

[FEAT] Date YYYY. MM. DD 형식에 맞도록 수정

---

src/apis/meeting/api.ts
src/pages/NewMeetingShare.tsx

close #257 
- 회원 일정 작성 여부 api path 변경했습니다!
- 공유하기 url에 www 추가했습니다!

[REFACTOR] 회원 일정 작성 여부 api path 변경

---

src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
src/components/common/FormLayout/index.tsx
src/components/common/ScheduleInput/ScheduleInput.styled.ts
src/components/features/CreateScheduleForm/ScheduleInputForm.tsx
src/components/features/EditScheduleForm/EditScheduleInputForm.tsx
src/components/features/TotalScheduleList/TotalScheduleList.tsx
src/pages/TimeCollection.tsx
src/pages/TotalSchedule.tsx

close #261 
- button padding-bottom 수정했습니다.
- padding 값 수정에 맞춰 height 조절이 필요한 부분 스타일 수정했습니다!

[FIX] 버튼 padding-bottom 수정

---

src/pages/Meeting.tsx

close #260 
- `dueDateTime`을 기준으로 현재와 가까운 모임을 가장 상단에 위치하도록 수정했습니다.

[FEAT] 현재 진행 중인 모임을 가장 상단에 위치하도록 수정

---

src/components/common/FloatingActionButton/FloatingActionButton.styled.ts

close #259 
- 위치 고정을 위해 FAB position 변경했습니다!

[FIX] FAB position 변경

---

src/components/features/MeetingList/index.tsx

close #273 
- 마감되지 않은 카드만 클릭 가능하도록
- 클릭 가능한 카드(=마감되지 않은 모임카드)에 cursor: pointer 적용
- 드래그 방지

[FEAT] 지난 모임 클릭 막기, 커서 변경

---

src/apis/schedule/api.ts

close #270 
- 일정 수정 API 경로 수정했습니다.

[FIX] 회원,비회원 api 수정
