dnd-side-project/dnd-11th-7-frontend

src/components/common/FlexBox/FlexBox.stories.tsx, src/components/common/FlexBox/FlexBox.styled.ts, src/components/common/FlexBox/FlexBox.types.ts
close #23 
- FlexBox에 margin과 padding을 쉽게 적용할 수 있도록 프롭을 추가합니다.
```tsx
<FlexBox margin={5} /> // 숫자만 입력 시 px로 변환 -> margin: '5px'
<FlexBox margin='5px 10px' /> // 문자열로 입력 시 그대로 적용 -> margin: '5px 10px'
// padding 도 동일
```
=> [FEAT] FlexBox에 margin, padding 프롭 추가

src/components/common/Progress/Progress.stories.tsx, src/components/common/Progress/Progress.styled.ts, src/components/common/Progress/Progress.types.ts, src/components/common/Progress/index.tsx
close #11 
- progress 컴포넌트, 스토리북 구현
- value값이 오를 수록 progress가 채워지는 컴포넌트 입니다.
- 추후에 피그마 > 컴포넌트 페이지 내에 완성본 올라오면 수정하도록 하겠습니다!
=> [FEAT] Progress 컴포넌트, 스토리북

src/components/common/Button/Button.stories.tsx, src/components/common/Button/Button.styled.ts, src/components/common/Button/Button.types.ts
close #37 
- width defalut 값을 `full` 로 변경해두었습니다. 현재 디자인 시안에서는 이미지 버튼을 제외하면 `fit`을 사용하지 않을 것 같습니다..! 
- 현재 버튼 색상이 한 가지인 것 같아 variant 옵션을 빼두었습니다.
- flex와 padding-top, padding-bottom 추가해두었습니다.
=> [FEAT] Button 컴포넌트 css 수정

src/components/common/Icon/Icon.stories.tsx, src/components/common/Icon/Icon.types.ts, src/components/common/Icon/index.tsx
close #51 
- 로고 같은 이미지의 경우 가로와 세로 높이가 달라 기존 Icon 컴포넌트 인터페이스로 대응할 수 없는 문제가 있어 width와 height를 각각 지정할 수 있도록 size 프롭에 타입을 추가합니다.
- as-is
```tsx
<Icon name='logo' size={20} />
```
- to-be
```tsx
<Icon name='logo' size={20} /> // OK
<Icon name='logo' size={{ width: 20, height: 10}} /> // OK
```
=> [FEAT] size 프롭에 width, height 레코드 타입 추가

src/components/common/Calendar/Calendar.stories.tsx, src/components/common/Calendar/Calendar.styled.ts, src/components/common/Calendar/Calendar.types.ts, src/components/common/Calendar/index.tsx, src/components/common/Calendar/useCalendar.tsx, src/constants/calendar.ts
close #12 
- Calendar 스토리북, 컴포넌트 구현하였습니다.
- 선택 불가능한 경우는 다음과 같습니다.
1. 이전 달
2. 오늘 이전
3. 오늘로부터 한달 뒤 (선택한 날짜가 없을 경우)
4. 오늘로부터 14일 이후 (선택한 날짜가 있을 경우)
- 디자인 사항이 2개라 날짜와 날짜 사이 배경 이미지색 입히는 건 추후에 진행하도록 하겠습니다...!
- 버튼이 피그마-컴포넌트에 있는 버튼하고 살짝 다른 것 같습니다! left, right 버튼 버전이 2개인지 여쭤봐야 할 것 같습니당
=> [FEAT] Calendar 컴포넌트, 스토리북

src/components/common/TextField/TextField.stories.tsx, src/components/common/TextField/TextField.types.ts, src/components/common/TextField/index.tsx, src/utils/validation.ts
close #101 
- input 값의 유효 상태를 다루기위해 둔 validState를 다음과 같은 이유로 제거합니다.
- onChange 핸들러가 호출될 때 계산으로 얻을 수 있는 상태 -> useState로 관리할 필요 없음
=> [REFACTOR] TextField에서 불필요한 상태 제거

.github/workflows/check-pull-request.yaml, .github/workflows/deploy-storybook.yaml, .github/workflows/deploy.yaml, .github/workflows/prepublish-storybook.yaml
close #88 
- PR이 작성된 경우와 Main에 머지가 된 경우에 스토리북 배포 액션을 돌리도록 설정하여 컴포넌트에 수정사항이 없음에도 스토리북 배포가 진행됩니다.
- 불필요한 스토리북 배포 + 알람 발생
- 구현한 컴포넌트를 디자이너에게 QA 받기 위하여 웹훅 설정을 했는데, 해당 알림에서 어떤 변경사항이 발생하여 수정되었는지 확인할 수 없는 번거로움이 존재합니다. (어떤 이유로 배포가 발생했는지 일일이 변경사항을 알려주기도 했음)
- src/components 폴더에 변경사항이 생긴 경우에만 스토리북 배포를 진행합니다.
- src/components 폴더에 변경사항이 있는 PR이 main 브랜치에 머지된 경우 스토리북 알람(디스코드 웹훅)을 전송합니다.
- 이때 PR의 제목을 알람에 포함시켜 어떤 변경사항이 발생했는지 파악할 수 있도록 합니다.
- src/components에 변경사항이 있는 경우에는 모두 액션이 실행되기 때문에, 스토리북을 사용하지 않는 컴포넌트를 변경해도 해당 액션이 실행됩니다.
- `스토리북 코드에 변경사항이 생긴 경우`로 한정하지 않은 이유는, 구현체나 디자인이 변경되어도 스토리북을 통해 확인할 수 있어야 한다고 판단했기 때문입니다.
=> [CHORE] /src/components에 변경사항이 생긴 경우에만 스토리북 배포

src/assets/icons/index.tsx, src/assets/icons/next.svg, src/assets/icons/plus.svg, src/assets/icons/prev.svg, src/components/common/Icon/Icon.stories.tsx, src/components/common/Icon/Icon.types.ts, src/components/common/Icon/index.tsx
close #123 
- scheduleInput에 사용할 next, plus Icon 추가했습니다.
- svg에 currentColor를 추가한 이후로 default color가 블랙이면 다음과 같이 보이는 현상이 존재했습니다. 따라서 storybook에서 디폴트 컬러 purple로 변경했습니다!
**변경 전**
**변경 후**
- prev 아이콘 까지 추가된 이후에 draft 풀겠습니다!
=> [FEAT] Icon 추가

src/components/common/SpeechBubble/SpeechBubble.stories.tsx, src/components/common/SpeechBubble/SpeechBubble.styled.ts, src/components/common/SpeechBubble/SpeechBubble.types.ts, src/components/common/SpeechBubble/index.tsx
close #118 
- 말풍선 컴포넌트와 스토리북을 추가합니다.
- 사용 예시
```tsx
<SpeechBubble>말풍선에 표시할 텍스트</SpeechBuuble>
```
- 렌더
- 말풍선의 커스텀 여부에 대해서는 고려하지 않았습니다. (e.g. 꼬리의 유무/위치, 말풍선 컬러 등)
=> [FEAT] 말풍선 컴포넌트, 스토리북

src/components/features/CreateMeetingForm/AnonymousForm.tsx, src/components/features/CreateMeetingForm/CategoryForm.tsx, src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx, src/components/features/CreateMeetingForm/DueDateForm.tsx, src/components/features/CreateMeetingForm/MeetingDateRangeForm.tsx, src/components/features/CreateMeetingForm/MeetingNameForm.tsx, src/components/features/CreateMeetingForm/MemberCountForm.tsx, src/components/features/CreateMeetingForm/types.ts, src/constants/meetingForm.ts, src/hooks/useFunnel.tsx, src/hooks/useMeetingFormState.tsx, src/pages/NewMeeting.tsx, src/types/meeting.ts
close #104 
폼 입력 완료하면 마지막에 부모(NewMeeting.tsx)가 갖게되는 formData의 모습 👇
- 각 퍼널 폼 내부에서 관리하는 지역 상태를 부모에서 관리하는 FormData 상태에 통합합니다.
- 부모 단에서 모든 입력 상태들을 알고 부모가 api 요청을 보내기 위함
- #102 -> #108 -> #106 순으로 머지 후 해당 PR 머지해야 합니다. (머지됐다는 가정 하에 작업했습니다)
=> [FEAT] 모임 생성 폼 상태 정리

src/components/features/CreateMeetingForm/AnonymousForm.tsx, src/components/features/CreateMeetingForm/CategoryForm.tsx, src/components/features/CreateMeetingForm/DueDateForm.tsx, src/components/features/CreateMeetingForm/MeetingDateRangeForm.tsx, src/components/features/CreateMeetingForm/MeetingNameForm.tsx, src/components/features/CreateMeetingForm/MemberCountForm.tsx, src/hooks/useMeetingFormProgressContext.tsx
#105 의 step PR 입니다 (PR 크기가 커질 것 같아서 쪼개서 작성합니다)
- 위 일정 확정 페이지가 추가됨에 따라, 퍼널의 progress가 7로 증가하는 문제를 해결합니다.
- `useMeetingFormProgressContext` 훅을 추가하여 progress가 6으로 유지되도록 합니다.
- 위 훅은 `useContext(FunnelProgressContext)`를 래핑한 훅입니다.
=> [FEAT] 퍼널 스텝에서 마지막(summary) 페이지 제외

src/components/common/PinInput/PinInput.styled.tsx, src/components/common/PinInput/index.tsx, src/hooks/usePinInput.tsx
close #134 
- PinInput 모바일 개선 작업했습니다.
- 한글이나 특수문자가 들어올 경우 Helper 메세지 띄웠습니다!
https://github.com/user-attachments/assets/7124fb88-c8ea-4f48-a603-8bed34443d4c
**문제 원인**
CSS의 캐스케이딩 특징 때문에 개발자가 정의한 스타일이 User Agent Stylesheet을 덮어쓰게 된다고합니당. 따라서 기본적으로 고유한 스타일을 적용시켜서 둥그렇게 보였나봐요.
**해결 방법**
아래 두가지 css 속성은 기본 UI 컨트롤의 외관을 제거해준다고 합니당
```
-webkit-appearance: none;
appearance: none;
```
border는 원래 제가 의도한 대로 `border-bottom`만 남기고, 그 테두리를 직각으로 만들기위해 `border-radius: 0;` 를 추가해줬어요!
=> [REFACTOR] PinInput 모바일 UI 개선

src/hooks/useSchedule.tsx
close #151 
- useSchedule훅에서 배열로 저장되고 있던 timeSlots value를 배열 객체로 변환했습니다.
=> [BUGFIX] useSchedule getSelectedTimeRanges 배열 객체로 변환

src/components/common/ScheduleLayout/ScheduleLayout.styled.ts, src/components/common/ScheduleLayout/index.tsx
close #190 
- ScheduleLayout Header backgroundColor 지정했습니다!
- 그라데이션이 purple에 투명도를 주기 때문에 Header 색상과 자연스럽게 이어지기 위해 다음과 같은 작업해줬습니다!
```
rgba(133, 123, 255) 0%,
rgba(133, 123, 255) 10%,
rgba(133, 123, 255, 0.9) 60%,
```
=> [FEAT] ScheduleLayout Header backgroundColor 지정

src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
close #186 
- FixedBottomButton `positon` 값 변경했습니다!
- `sticky` 로 적용하면 버튼이 가운데 뜹니다..🤔 (왜 뜨는거일까욥..) 따라서 `fixed`로 구현했습니다!
=> [FIX] FixedBottomButton css 수정

src/components/common/ScheduleInput/ScheduleInput.type.ts, src/components/common/ScheduleInput/index.tsx, src/components/common/TimeRangePicker/TimeRangePicker.styled.ts, src/components/common/TimeRangePicker/TimeRangePicker.type.ts, src/components/common/TimeRangePicker/index.tsx
close #213 
- ScheduleInput/TimeRangePicker totalPeopleNum, meetingTimeList Props 추가했습니다!
- 일정 한눈에 보기를 진행할 때  모임일정 시간 조회 API의 meetingTimeList.memberNames.length을 활용하여 해당 시간대에 투표한 인원이 몇명인지 보여주는데 사용했습니다. 
- 총인원이 4명이라면 color 색상이 너무 연하기 때문에 totalPeopleNum을 받아 `(10 - totalPeopleNum)` 을 baseColor로 지정하고, `10 - baseIndex + meetingTimeList.memberNames.length(props.intensity)` 값을 더해서 계산했습니당
```
meetingTimeList": [
{
"memberNames": [
"멤버",
"멤버",
"dd"
],
"startTime": "2024-09-26T15:00:00",
"endTime": "2024-09-26T16:00:00",
"rank": 1.0
},
{
"memberNames": [
"멤버",
"멤버",
"dd"
],
"startTime": "2024-09-26T16:00:00",
"endTime": "2024-09-26T17:00:00",
"rank": 1.0
},
];
```
=> [FEAT] ScheduleInput/TimeRangePicker totalPeopleNum, meetingTimeList Props 추가

src/components/common/TimeRangePicker/TimeRangePicker.styled.ts, src/components/common/TimeRangePicker/index.tsx, src/components/features/MeetingDetail/MemberScheduleCard.tsx, src/pages/TimeCollection.tsx, src/routes/route.tsx
close #223 
- 일정 한눈에 보기 페이지 API 연결진행했습니다.
- `totalTime` , `result` 보다 조금 더 직관적인 route 이름이 필요할 것 같습니다! 둘 다 전체 일정의 시간에 관한 데이터들을 보여줘서 고민이됩니당
=> [FEAT] 일정 한눈에 보기 페이지 API 연결

src/apis/index.ts, src/apis/schedule/api.ts, src/apis/schedule/mutations.ts, src/apis/schedule/queries.ts, src/apis/schedule/type.ts, src/components/common/TimeRangePicker/index.tsx, src/components/features/CreateScheduleForm/ScheduleInputForm.tsx, src/components/features/CreateScheduleForm/types.ts, src/components/features/EditScheduleForm/EditScheduleContent.tsx, src/components/features/EditScheduleForm/EditScheduleForm.stories.tsx, src/components/features/EditScheduleForm/PinInputForm.tsx, src/components/features/EditScheduleForm/types.ts, src/components/features/TotalScheduleList/TotalScheduleList.tsx, src/pages/EditSchedule.tsx, src/pages/NewSchedule.tsx, src/utils/formatTime.ts
close #225
- 일정 수정 API 연결했습니다.
- 회원의 일정 수정 시 데이터가 undefined로 초기화 된 이후 데이터가 들어오는 것을 확인했습니다. 따라서 코드에 해당 조건을 추가했습니다.
- 일정 수정페이지로 진입시 200밀리초 동안 빈 화면이 뜹니다. API를 불러오는 동안 생기는 문제 상황 같습니다. `loadingPage`가 있으면 좋을 것 같다고 느꼈습니당.
```
{scheduleData?.dateOfScheduleList && (
<ScheduleInputForm
uuid={uuid}
edit={true}
dateOfScheduleList={scheduleData?.dateOfScheduleList}
onPrev={() => (accessToken ? navigate(`/${uuid}`) : setStep('식별자입력'))}
onNext={handleSubmitMeeting}
setValue={updateSchedule}
/>
)}
```
=> [FEAT] 일정 수정 API 연결

src/components/common/Modal/index.tsx, src/components/features/EditScheduleForm/EditScheduleContent.tsx, src/components/features/EditScheduleForm/EditScheduleForm.stories.tsx, src/constants/scheduleForm.ts, src/pages/EditSchedule.tsx, src/pages/NewSchedule.tsx
close #235
- 일정 입력/수정 시 Modal 내 navigate 수정했습니다.
**공통**
- 일정 수정 시 모달 내 `홈으로/결과 확인하기` 버튼 노출
**회원**
1. 일정 생성 시 모달 내 `수정/결과 확인` 버튼 노출
**비회원**
1. 일정 생성 시 Pin 번호 공유하는 페이지 이동
=> [FEAT] 일정 입력/수정 시 Modal 내 navigate 수정

src/apis/meeting/api.ts, src/apis/meeting/queries.ts, src/components/features/MeetingDetail/MemberScheduleCard.tsx, src/pages/MeetingDetail.tsx
close #238 
- 회원 일정 작성 여부 조회 api 연결했습니다.
- 일정 입력 후에는 일정 수정 버튼을 보여주도록 조건 추가했습니다. 
- 버튼에 로딩 상태가 추가되는 것을 고려하여 `renderButton` 함수를 따로 구현했습니다. 
- 회원인 경우에만 해당 api를 호출해야 하기 때문에, `useQuery`의 `enabled` 옵션을 통해 구분했습니다. 더 좋은 방법 있다면 얘기해주세요!
=> [FEAT] 회원 일정 작성 여부 조회 api 연결

src/components/features/MeetingDetail/MemberList.tsx
close #240 
- MemberList에서 리더가 가장 처음에 위치하도록 수정했습니다.
=> [FEAT] MemberList에서 리더가 가장 처음에 위치하도록 수정

src/hooks/useSchedule.tsx
close #244 
- 일정 수정의 경우 `savedTimeSlots`에 데이터를 저장하고 있습니다. 일정 수정시 `savedTimeSlots`에 변경된 값을 할당하지 않아 문제 상황이 발생하였고, `savedTimeSlots`에 변경된 값을 할당하여 해결하였습니다.
=> [BUGFIX] 일정 수정 시 변경된 일정이 저장이 안되는 버그

src/components/features/KakaoLoginButton/index.tsx, src/pages/Landing.tsx
=> [FEAT] 랜딩 페이지 시작하기 버튼을 카카오톡 로그인 버튼으로 교체

src/components/features/CreateMeetingForm/DueDateForm.tsx
close #271 
- 원인
- 날짜만 따지면 되는데, 시간까지 비교해서 발생한 문제
- e.g. 모임 일정 시작 시간(meetingStartDate)은 `2024-11-06T00:00:00`인데, 일정 입력 마감 기한 폼에 접근한 시간(accessDate)는 2024-11-06T01:01:01이라면 접근한 시간이 더 늦어서 `오늘` 선택지가 노출되지 않음
- 해결
- 시간 떼고 비교
- 서버에 시간을 포함한 YYYY-MM-DDThh:mm:ss 포맷으로 요청을 보내야해서, 스위치 버튼의 value 값에 포맷팅해주었음
=> [BUGFIX] 일정 입력 마감 기한 선택지 노출되도록

src/apis/member/api.ts, src/apis/member/type.ts, src/hooks/useAuth.tsx, src/lib/axios.ts
close #278 
- accessToken을 response의 헤더로 받지 않고 body로 받도록 수정되었습니다.
- 인터셉터에 의해 무한 reissue 요청이 발생하지 않도록 인터셉터 로직을 수정합니다.
=> [BUGFIX] reissue 무한 요청 동작 픽스

src/apis/schedule/api.ts, src/components/features/CreateMeetingForm/DueDateForm.tsx
close #282 
- 일정 조회 API 경로 수정했습니다.
- 모집 마감 기한 필터링 로직에서 시간까지 고려되어 시작 날짜가 오늘인 경우 `dayjs('2024-12-03T23:59:59').isSameOrBefore(dayjs('2024-12-03'))` 조건이 false로 평가되는 문제 상황이 있었습니다. (시간이 존재 하지 않을 경우 00:00:00이 적용됩니다.)
- 날짜만 비교하도록 `startOf('day')` 사용했습니다!
=> [FIX] 일정 조회 API 경로 수정
